onerror {resume}
quietly virtual function -install sim:/Pratica1_Part3 -env sim:/Pratica1_Part3 { &{/Pratica1_Part3/outWord[8], /Pratica1_Part3/outWord[7], /Pratica1_Part3/outWord[6] }} ValLRUDirty
quietly virtual function -install sim:/Pratica1_Part3 -env sim:/Pratica1_Part3 { &{/Pratica1_Part3/outWord[5], /Pratica1_Part3/outWord[4], /Pratica1_Part3/outWord[3] }} Tag
quietly virtual function -install sim:/Pratica1_Part3 -env sim:/Pratica1_Part3 { &{/Pratica1_Part3/outWord[2], /Pratica1_Part3/outWord[1], /Pratica1_Part3/outWord[0] }} Data
quietly virtual signal -install sim:/Pratica1_Part3 {sim:/Pratica1_Part3/MemWays[3]  } Conjunto3
quietly virtual signal -install sim:/Pratica1_Part3 {sim:/Pratica1_Part3/MemWays[2]  } Conjunto2
quietly virtual signal -install sim:/Pratica1_Part3 {sim:/Pratica1_Part3/MemWays[1]  } Conjunto1
quietly virtual signal -install sim:/Pratica1_Part3 {sim:/Pratica1_Part3/MemWays[0]  } Conjunto0
quietly WaveActivateNextPane {} 0
add wave -noupdate -color Yellow /Pratica1_Part3/clock
add wave -noupdate -color Blue -subitemconfig {{/Pratica1_Part3/address[4]} {-color Blue} {/Pratica1_Part3/address[3]} {-color Blue} {/Pratica1_Part3/address[2]} {-color Blue} {/Pratica1_Part3/address[1]} {-color Blue} {/Pratica1_Part3/address[0]} {-color Blue}} /Pratica1_Part3/address
add wave -noupdate -color Red /Pratica1_Part3/wren
add wave -noupdate -color Salmon -subitemconfig {{/Pratica1_Part3/write[2]} {-color Salmon} {/Pratica1_Part3/write[1]} {-color Salmon} {/Pratica1_Part3/write[0]} {-color Salmon}} /Pratica1_Part3/write
add wave -noupdate -expand -group Sinalizadores -color White /Pratica1_Part3/hit
add wave -noupdate -expand -group Sinalizadores -color Gray60 /Pratica1_Part3/writeBack
add wave -noupdate -expand -group outWord -color Magenta -subitemconfig {{/Pratica1_Part3/outWord[8]} {-color Magenta} {/Pratica1_Part3/outWord[7]} {-color Magenta} {/Pratica1_Part3/outWord[6]} {-color Magenta}} /Pratica1_Part3/ValLRUDirty
add wave -noupdate -expand -group outWord -color {Medium Sea Green} -subitemconfig {{/Pratica1_Part3/outWord[5]} {-color {Medium Sea Green}} {/Pratica1_Part3/outWord[4]} {-color {Medium Sea Green}} {/Pratica1_Part3/outWord[3]} {-color {Medium Sea Green}}} /Pratica1_Part3/Tag
add wave -noupdate -expand -group outWord -color {Blue Violet} -subitemconfig {{/Pratica1_Part3/outWord[2]} {-color {Blue Violet}} {/Pratica1_Part3/outWord[1]} {-color {Blue Violet}} {/Pratica1_Part3/outWord[0]} {-color {Blue Violet}}} /Pratica1_Part3/Data
add wave -noupdate -expand -group Cache -color {Medium Aquamarine} -subitemconfig {{/Pratica1_Part3/MemWays[0][0]} {-color {Medium Aquamarine} -height 15} {/Pratica1_Part3/MemWays[0][0][8]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][0][7]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][0][6]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][0][5]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][0][4]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][0][3]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][0][2]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][0][1]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][0][0]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][1]} {-color {Medium Aquamarine} -height 15} {/Pratica1_Part3/MemWays[0][1][8]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][1][7]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][1][6]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][1][5]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][1][4]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][1][3]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][1][2]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][1][1]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][1][0]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][2]} {-color {Medium Aquamarine} -height 15} {/Pratica1_Part3/MemWays[0][2][8]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][2][7]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][2][6]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][2][5]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][2][4]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][2][3]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][2][2]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][2][1]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][2][0]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][3]} {-color {Medium Aquamarine} -height 15} {/Pratica1_Part3/MemWays[0][3][8]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][3][7]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][3][6]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][3][5]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][3][4]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][3][3]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][3][2]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][3][1]} {-color {Medium Aquamarine}} {/Pratica1_Part3/MemWays[0][3][0]} {-color {Medium Aquamarine}}} /Pratica1_Part3/Conjunto0
add wave -noupdate -expand -group Cache -color Aquamarine -subitemconfig {{/Pratica1_Part3/MemWays[1][0]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][0][8]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][0][7]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][0][6]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][0][5]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][0][4]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][0][3]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][0][2]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][0][1]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][0][0]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][1]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][1][8]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][1][7]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][1][6]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][1][5]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][1][4]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][1][3]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][1][2]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][1][1]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][1][0]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][2]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][2][8]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][2][7]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][2][6]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][2][5]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][2][4]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][2][3]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][2][2]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][2][1]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][2][0]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][3]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][3][8]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][3][7]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][3][6]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][3][5]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][3][4]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][3][3]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][3][2]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][3][1]} {-color Aquamarine} {/Pratica1_Part3/MemWays[1][3][0]} {-color Aquamarine}} /Pratica1_Part3/Conjunto1
add wave -noupdate -expand -group Cache -color Turquoise -subitemconfig {{/Pratica1_Part3/MemWays[2][0]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][0][8]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][0][7]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][0][6]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][0][5]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][0][4]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][0][3]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][0][2]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][0][1]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][0][0]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][1]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][1][8]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][1][7]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][1][6]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][1][5]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][1][4]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][1][3]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][1][2]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][1][1]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][1][0]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][2]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][2][8]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][2][7]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][2][6]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][2][5]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][2][4]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][2][3]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][2][2]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][2][1]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][2][0]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][3]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][3][8]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][3][7]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][3][6]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][3][5]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][3][4]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][3][3]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][3][2]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][3][1]} {-color Turquoise} {/Pratica1_Part3/MemWays[2][3][0]} {-color Turquoise}} /Pratica1_Part3/Conjunto2
add wave -noupdate -expand -group Cache -color Cyan -subitemconfig {{/Pratica1_Part3/MemWays[3][0]} {-color Cyan} {/Pratica1_Part3/MemWays[3][0][8]} {-color Cyan} {/Pratica1_Part3/MemWays[3][0][7]} {-color Cyan} {/Pratica1_Part3/MemWays[3][0][6]} {-color Cyan} {/Pratica1_Part3/MemWays[3][0][5]} {-color Cyan} {/Pratica1_Part3/MemWays[3][0][4]} {-color Cyan} {/Pratica1_Part3/MemWays[3][0][3]} {-color Cyan} {/Pratica1_Part3/MemWays[3][0][2]} {-color Cyan} {/Pratica1_Part3/MemWays[3][0][1]} {-color Cyan} {/Pratica1_Part3/MemWays[3][0][0]} {-color Cyan} {/Pratica1_Part3/MemWays[3][1]} {-color Cyan} {/Pratica1_Part3/MemWays[3][1][8]} {-color Cyan} {/Pratica1_Part3/MemWays[3][1][7]} {-color Cyan} {/Pratica1_Part3/MemWays[3][1][6]} {-color Cyan} {/Pratica1_Part3/MemWays[3][1][5]} {-color Cyan} {/Pratica1_Part3/MemWays[3][1][4]} {-color Cyan} {/Pratica1_Part3/MemWays[3][1][3]} {-color Cyan} {/Pratica1_Part3/MemWays[3][1][2]} {-color Cyan} {/Pratica1_Part3/MemWays[3][1][1]} {-color Cyan} {/Pratica1_Part3/MemWays[3][1][0]} {-color Cyan} {/Pratica1_Part3/MemWays[3][2]} {-color Cyan} {/Pratica1_Part3/MemWays[3][2][8]} {-color Cyan} {/Pratica1_Part3/MemWays[3][2][7]} {-color Cyan} {/Pratica1_Part3/MemWays[3][2][6]} {-color Cyan} {/Pratica1_Part3/MemWays[3][2][5]} {-color Cyan} {/Pratica1_Part3/MemWays[3][2][4]} {-color Cyan} {/Pratica1_Part3/MemWays[3][2][3]} {-color Cyan} {/Pratica1_Part3/MemWays[3][2][2]} {-color Cyan} {/Pratica1_Part3/MemWays[3][2][1]} {-color Cyan} {/Pratica1_Part3/MemWays[3][2][0]} {-color Cyan} {/Pratica1_Part3/MemWays[3][3]} {-color Cyan} {/Pratica1_Part3/MemWays[3][3][8]} {-color Cyan} {/Pratica1_Part3/MemWays[3][3][7]} {-color Cyan} {/Pratica1_Part3/MemWays[3][3][6]} {-color Cyan} {/Pratica1_Part3/MemWays[3][3][5]} {-color Cyan} {/Pratica1_Part3/MemWays[3][3][4]} {-color Cyan} {/Pratica1_Part3/MemWays[3][3][3]} {-color Cyan} {/Pratica1_Part3/MemWays[3][3][2]} {-color Cyan} {/Pratica1_Part3/MemWays[3][3][1]} {-color Cyan} {/Pratica1_Part3/MemWays[3][3][0]} {-color Cyan}} /Pratica1_Part3/Conjunto3
TreeUpdate [SetDefaultTree]
quietly WaveActivateNextPane
add wave -noupdate /Pratica1_Part3/address
add wave -noupdate /Pratica1_Part3/wren
add wave -noupdate /Pratica1_Part3/write
add wave -noupdate /Pratica1_Part3/clock
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {80 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 210
configure wave -valuecolwidth 98
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {926 ps}
view wave 
wave clipboard store
wave create -driver freeze -pattern constant -value 0 -range 4 0 -starttime 0ps -endtime 1000ps sim:/Pratica1_Part3/address 
WaveExpandAll -1
wave create -driver freeze -pattern constant -value 0 -starttime 0ps -endtime 1000ps sim:/Pratica1_Part3/wren 
wave create -driver freeze -pattern constant -value 0 -range 2 0 -starttime 0ps -endtime 1000ps sim:/Pratica1_Part3/write 
WaveExpandAll -1
wave create -driver freeze -pattern clock -initialvalue 0 -period 100ps -dutycycle 50 -starttime 0ps -endtime 1000ps sim:/Pratica1_Part3/clock 
WaveCollapseAll -1
wave clipboard restore
